Repository AY2223S1-CS2103T-T15-3/tp, pull requests merged in 2022-11, with the labels that each got.

#253 Enhance UG flow and phrasing
  docs/UserGuide.md
Labels: type.UG

#255 Fix UG formatting error
  docs/UserGuide.md
Labels: type.UG

#231 Remove unnecessary UI config and help table
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/resources/images/help_table.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Medium

#267 Update PPP for Fanny
  docs/UserGuide.md
  docs/images/user-guide/tuthub.png
  docs/team/fannyjian.md
Labels: type.AboutUs

#276 Update Marcus' PPP
  docs/team/marcuslowhuiyu.md
Labels: priority.High, type.AboutUs

#277 Edit UG formatting and add screenshots
  docs/UserGuide.md
  docs/images/user-guide/comment.png
  docs/images/user-guide/detailsPane.png
  docs/images/user-guide/layout.png
  docs/images/user-guide/mail.png
  docs/images/user-guide/view.png
Labels: type.UG

#282 Improve UG format consistency
  docs/UserGuide.md
  docs/images/user-guide/add.png
  docs/images/user-guide/find-tag.png
  docs/images/user-guide/find.png
Labels: type.UG

#288 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandExecutorClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/CommandExecutorClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/fannyjian.md
  docs/team/marcuslowhuiyu.md
  docs/team/t1mzzz.md
Labels: type.DG

#293 Update glossary, user stories and testing in DG
  docs/DeveloperGuide.md
  docs/_includes/head.html
  docs/images/page-logo.png
  docs/images/tuthub.png
Labels: type.DG

#294 Bold UG headers and update warning color
  docs/UserGuide.md
Labels: type.UG

#296 Fix section link in UG and update tip color to yellow
  docs/UserGuide.md
  docs/_sass/minima/custom-variables.scss
Labels: type.UG

#312 Update `view` sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewSequenceDiagram.png
  docs/images/img.png
Labels: type.DG

#311 Modify DG for comment function
  docs/DeveloperGuide.md
  docs/diagrams/CommentSequenceDiagram.puml
  docs/images/CommentSequenceDiagram.png
Labels: priority.High, type.DG

#297 Update DG for deletecomment command
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommentSequenceDiagram.puml
  docs/images/DeleteCommentSequenceDiagram.png
Labels: priority.High, type.DG

#315 Check for errors in UG
  docs/UserGuide.md
  docs/images/user-guide/edit.png
Labels: type.UG

#317 Update DG, UG and `fannyjian.md`
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/team/fannyjian.md
  src/main/resources/images/help_table.png
Labels: type.Bug, type.DG

#316 Add test instructions for comment and deletecomment
  docs/DeveloperGuide.md
Labels: priority.High, type.DG

#321 Update DG for `view` and `edit` features
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/diagrams/ViewSequenceUiDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/images/ViewSequenceDiagram.png
  docs/images/ViewSequenceUiDiagram.png
  docs/team/fannyjian.md
Labels: priority.High, type.DG

#330 Minor fixing of format in use cases
  docs/DeveloperGuide.md
  docs/team/fannyjian.md
Labels: type.DG
