Repository AY2223S1-CS2103T-T15-3/tp, pull requests merged in 2022-09, with the labels that each got.

#17 Update user guide
  docs/UserGuide.md
Labels: documentation, type.UG

#18 Update user guide exit feature
  docs/UserGuide.md
Labels: documentation, type.UG

#21 Update DG with user profile, value proposition and user stories
  docs/DeveloperGuide.md
Labels: documentation, type.DG

#22 Add PPP
  docs/team/jia-han.md
Labels: type.Task

#48 Add UI mockup
  docs/images/Ui.png
Labels: documentation

#49 Update about us (Fanny)
  docs/AboutUs.md
  docs/images/fannyjian.png
Labels: documentation, type.AboutUs

#51 Fix skeletal PPP formatting error
  docs/team/fannyjian.md
  docs/team/jia-han.md
  docs/team/leirdas.md
  docs/team/t1mzzz.md
Labels: type.Task, priority.High

#52 Update user guide for save feature
  docs/UserGuide.md
Labels: documentation

#53 Add skeletal PPP
  docs/team/marcuslowhuiyu.md
Labels: documentation

#55 Update AboutUs
  docs/AboutUs.md
  docs/images/jia-han.png
Labels: documentation

#56 Update about us
  docs/AboutUs.md
  docs/images/leirdas.png
Labels: type.AboutUs

#57 Update UserGuide to eliminate any trace of AB3
  docs/UserGuide.md
Labels: documentation, type.Task, type.UG

#59 Update DG (use cases, NFRs, glossary)
  docs/DeveloperGuide.md
Labels: documentation, type.Task, type.DG
