Repository AY2223S1-CS2103T-T15-3/tp, pull requests merged in 2022-10, with the labels that each got.

#60 Add minor changes to DG
  docs/DeveloperGuide.md
Labels: documentation, type.Task, type.DG

#65 Update delete messages
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Story, priority.High

#66 Edit exit command
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: type.Story, priority.High

#67 Update user guide
  docs/UserGuide.md
Labels: type.UG

#77 Add module and year fields to Person model
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Year.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/ModuleTest.java
  src/test/java/seedu/address/model/person/YearTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#76 Add StudentId model, add JUnit tests for StudentId
  src/main/java/seedu/address/model/person/StudentId.java
  src/test/java/seedu/address/model/person/StudentIdTest.java
Labels: type.Task, priority.High

#75 Update UG, DG, and index with new info
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation, type.Task, type.DG, type.UG

#80 Update add command to store StudentId
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#81 Add comment class
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CommentCommandParser.java
  src/main/java/seedu/address/model/person/Comment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommentUnfilteredList.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High

#89 Add feature so that users are able to search TAs by modules that they teach
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/FindByModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindByModuleCommandParser.java
  src/main/java/seedu/address/model/person/ModuleContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/FindByModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByModuleCommandParserTest.java
  src/test/java/seedu/address/model/person/ModuleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#90 Remove Address model
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/ModuleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#93 Update UG to include all v1.2 commands
  docs/UserGuide.md
Labels: priority.High, type.UG

#95 Update help table
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/resources/images/help_table.png
Labels: type.Story, priority.High

#107 Add teaching nomination to tutor profile
  src/main/java/tuthub/logic/commands/AddCommand.java
  src/main/java/tuthub/logic/commands/CommentCommand.java
  src/main/java/tuthub/logic/commands/EditCommand.java
  src/main/java/tuthub/logic/parser/AddCommandParser.java
  src/main/java/tuthub/logic/parser/CliSyntax.java
  src/main/java/tuthub/logic/parser/EditCommandParser.java
  src/main/java/tuthub/logic/parser/ParserUtil.java
  src/main/java/tuthub/model/tutor/TeachingNomination.java
  src/main/java/tuthub/model/tutor/Tutor.java
  src/main/java/tuthub/model/util/SampleDataUtil.java
  src/main/java/tuthub/storage/JsonAdaptedTutor.java
  src/test/data/JsonSerializableTuthubTest/duplicateTutorTuthub.json
  src/test/data/JsonSerializableTuthubTest/invalidTutorTuthub.json
  src/test/data/JsonSerializableTuthubTest/typicalTutorsTuthub.json
  src/test/java/tuthub/logic/LogicManagerTest.java
  src/test/java/tuthub/logic/commands/CommandTestUtil.java
  src/test/java/tuthub/logic/commands/EditTutorDescriptorTest.java
  src/test/java/tuthub/logic/parser/AddCommandParserTest.java
  src/test/java/tuthub/model/person/TeachingNominationTest.java
  src/test/java/tuthub/storage/JsonAdaptedTutorTest.java
  src/test/java/tuthub/testutil/EditTutorDescriptorBuilder.java
  src/test/java/tuthub/testutil/TutorBuilder.java
  src/test/java/tuthub/testutil/TutorUtil.java
  src/test/java/tuthub/testutil/TypicalTutors.java
Labels: type.Task

#110 Add tests for TeachingNomination model
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  src/test/java/tuthub/model/person/TeachingNominationTest.java
  src/test/java/tuthub/model/tutor/EmailTest.java
  src/test/java/tuthub/model/tutor/ModuleContainsKeywordsPredicateTest.java
  src/test/java/tuthub/model/tutor/ModuleTest.java
  src/test/java/tuthub/model/tutor/NameContainsKeywordsPredicateTest.java
  src/test/java/tuthub/model/tutor/NameTest.java
  src/test/java/tuthub/model/tutor/PhoneTest.java
  src/test/java/tuthub/model/tutor/StudentIdTest.java
  src/test/java/tuthub/model/tutor/TeachingNominationTest.java
  src/test/java/tuthub/model/tutor/TutorTest.java
  src/test/java/tuthub/model/tutor/UniqueTutorListTest.java
  src/test/java/tuthub/model/tutor/YearTest.java
Labels: type.Task, priority.High

#116 Delete Address model
  src/main/java/tuthub/model/tutor/Address.java
Labels: type.Task, priority.High

#114 Add Rating model, update UG with Rating
  docs/UserGuide.md
  src/main/java/tuthub/logic/commands/AddCommand.java
  src/main/java/tuthub/logic/commands/CommentCommand.java
  src/main/java/tuthub/logic/commands/EditCommand.java
  src/main/java/tuthub/logic/parser/AddCommandParser.java
  src/main/java/tuthub/logic/parser/CliSyntax.java
  src/main/java/tuthub/logic/parser/EditCommandParser.java
  src/main/java/tuthub/logic/parser/ParserUtil.java
  src/main/java/tuthub/model/tutor/Name.java
  src/main/java/tuthub/model/tutor/Rating.java
  src/main/java/tuthub/model/tutor/StudentId.java
  src/main/java/tuthub/model/tutor/Tutor.java
  src/main/java/tuthub/model/util/SampleDataUtil.java
  src/main/java/tuthub/storage/JsonAdaptedTutor.java
  src/test/data/JsonSerializableTuthubTest/duplicateTutorTuthub.json
  src/test/data/JsonSerializableTuthubTest/typicalTutorsTuthub.json
  src/test/java/tuthub/logic/LogicManagerTest.java
  src/test/java/tuthub/logic/commands/CommandTestUtil.java
  src/test/java/tuthub/logic/parser/AddCommandParserTest.java
  src/test/java/tuthub/model/tutor/RatingTest.java
  src/test/java/tuthub/storage/JsonAdaptedTutorTest.java
  src/test/java/tuthub/testutil/EditTutorDescriptorBuilder.java
  src/test/java/tuthub/testutil/TutorBuilder.java
  src/test/java/tuthub/testutil/TutorUtil.java
  src/test/java/tuthub/testutil/TypicalTutors.java
Labels: type.Task, priority.High, type.UG

#118 Enable assertions
  build.gradle
Labels: type.Task, priority.High

#121 Add tests and documentation for View Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/test/java/tuthub/logic/commands/CommandResultTest.java
  src/test/java/tuthub/logic/commands/CommandTestUtil.java
  src/test/java/tuthub/logic/commands/ViewCommandTest.java
  src/test/java/tuthub/logic/parser/TuthubParserTest.java
  src/test/java/tuthub/logic/parser/ViewCommandParserTest.java
Labels: documentation, type.DG, type.UG

#127 Add `SortCommand` to Tuthub
  docs/UserGuide.md
  src/main/java/tuthub/logic/commands/ListCommand.java
  src/main/java/tuthub/logic/commands/SortCommand.java
  src/main/java/tuthub/logic/parser/ParserUtil.java
  src/main/java/tuthub/logic/parser/SortCommandParser.java
  src/main/java/tuthub/logic/parser/TuthubParser.java
  src/main/java/tuthub/model/Model.java
  src/main/java/tuthub/model/ModelManager.java
  src/main/java/tuthub/model/tutor/SortByRatingComparator.java
  src/main/java/tuthub/model/tutor/SortByTeachingNominationComparator.java
  src/test/java/tuthub/logic/commands/AddCommandTest.java
  src/test/java/tuthub/logic/commands/SortCommandTest.java
  src/test/java/tuthub/logic/parser/SortCommandParserTest.java
  src/test/java/tuthub/model/tutor/SortByRatingComparatorTest.java
  src/test/java/tuthub/model/tutor/SortByTeachingNominationComparatorTest.java
Labels: type.Story, priority.High

#137 Fix display issue after adding multiple module tags
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TutorDetailsPanel.fxml
  src/main/resources/view/TutorListCard.fxml
Labels: bug

#145 Add hide details function
  src/main/java/tuthub/ui/MainWindow.java
  src/main/java/tuthub/ui/TutorListCard.java
  src/main/resources/view/TutorListCard.fxml
Labels: type.Bug, severity.Medium

#152 Update developer guide for View command
  docs/DeveloperGuide.md
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewSequenceDiagram.png
  docs/images/img.png
  src/main/java/tuthub/logic/commands/CommandResult.java
Labels: type.DG

#154 Update version in `MainApp` to 1.2.1
  src/main/java/tuthub/MainApp.java
Labels: type.Task, priority.High

#156 Add `sort` to DG
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortSequenceDiagram.png
Labels: priority.High, type.DG

#155 Add `add` in developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/team/fannyjian.md
  docs/team/jia-han.md
Labels: type.DG

#159 Fix resolution for `SortSequenceDiagram`
  docs/images/SortSequenceDiagram.png
Labels: priority.High, type.DG

#158 Update DG for comment command
  docs/DeveloperGuide.md
  docs/diagrams/CommentSequenceDiagram.puml
  docs/images/CommentSequenceDiagram.png
  src/main/java/tuthub/model/tutor/CommentList.java
Labels: priority.High, type.DG

#164 Add Introduction and About Sections to User Guide
  docs/UserGuide.md
  docs/images/user-guide/layout.png
  docs/images/user-guide/start.png
  src/main/java/tuthub/model/util/SampleDataUtil.java
Labels: type.UG

#165 Make changes to find feature in UG
  docs/UserGuide.md
Labels: type.UG

#166 Add glossary section and edit formatting
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/index.md
  src/main/resources/images/help_table.png
Labels: type.UG

#162 Add `MailCommand`
  docs/UserGuide.md
  src/main/java/tuthub/logic/commands/MailCommand.java
  src/main/java/tuthub/logic/commands/SortCommand.java
  src/main/java/tuthub/logic/parser/MailCommandParser.java
  src/main/java/tuthub/logic/parser/TuthubParser.java
  src/test/java/tuthub/logic/commands/MailCommandTest.java
  src/test/java/tuthub/logic/commands/SortCommandTest.java
  src/test/java/tuthub/logic/parser/MailCommandParserTest.java
Labels: priority.High

#170 Update `Email` to handle NUS emails
  src/main/java/tuthub/model/tutor/Email.java
  src/main/java/tuthub/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableTuthubTest/duplicateTutorTuthub.json
  src/test/data/JsonSerializableTuthubTest/typicalTutorsTuthub.json
  src/test/java/tuthub/logic/commands/CommandTestUtil.java
  src/test/java/tuthub/logic/commands/FindByEmailCommandTest.java
  src/test/java/tuthub/logic/parser/ParserUtilTest.java
  src/test/java/tuthub/model/tutor/EmailContainsKeywordsPredicateTest.java
  src/test/java/tuthub/model/tutor/EmailTest.java
  src/test/java/tuthub/model/tutor/ModuleContainsKeywordsPredicateTest.java
  src/test/java/tuthub/model/tutor/NameContainsKeywordsPredicateTest.java
  src/test/java/tuthub/model/tutor/TagContainsKeywordsPredicateTest.java
  src/test/java/tuthub/model/tutor/YearContainsKeywordPredicateTest.java
  src/test/java/tuthub/storage/JsonAdaptedTutorTest.java
  src/test/java/tuthub/testutil/TutorBuilder.java
  src/test/java/tuthub/testutil/TypicalTutors.java
Labels: priority.Medium

#177 Fix success message
  src/main/java/tuthub/model/tutor/Tutor.java
Labels: type.Bug

#169 Modify comments to be list
  src/main/java/tuthub/logic/commands/CommentCommand.java
  src/main/java/tuthub/logic/commands/DeleteCommentCommand.java
  src/main/java/tuthub/logic/commands/EditCommand.java
  src/main/java/tuthub/logic/parser/AddCommandParser.java
  src/main/java/tuthub/logic/parser/DeleteCommentCommandParser.java
  src/main/java/tuthub/logic/parser/TuthubParser.java
  src/main/java/tuthub/model/tutor/CommentList.java
  src/main/java/tuthub/model/tutor/Tutor.java
  src/main/java/tuthub/model/util/SampleDataUtil.java
  src/main/java/tuthub/storage/JsonAdaptedTutor.java
  src/main/java/tuthub/ui/TutorDetailsPanel.java
  src/main/resources/view/TutorDetailsPanel.fxml
  src/test/data/JsonSerializableTuthubTest/duplicateTutorTuthub.json
  src/test/data/JsonSerializableTuthubTest/typicalTutorsTuthub.json
  src/test/java/tuthub/logic/LogicManagerTest.java
  src/test/java/tuthub/logic/commands/AddCommentUnfilteredList.java
  src/test/java/tuthub/storage/JsonAdaptedTutorTest.java
  src/test/java/tuthub/testutil/TutorBuilder.java
Labels: priority.Medium

#181 Update UG for comment and deletecomment
  docs/UserGuide.md
Labels: priority.High, type.UG

#198 Fix help table and additional comments section in UI
  docs/images/helpMessage.png
  src/main/java/tuthub/ui/HelpWindow.java
  src/main/java/tuthub/ui/TutorDetailsPanel.java
Labels: type.Bug

#199 Update sample email for `add` and `edit` command message
  src/main/java/tuthub/logic/commands/AddCommand.java
  src/main/java/tuthub/logic/commands/EditCommand.java
Labels: type.Bug

#249 Enhance UG formatting and phrasing
  docs/UserGuide.md
  docs/images/user-guide/detailsPane.png
Labels: type.Bug, type.UG
